---
title: "Ny test px-fil"
author: "LarsP"
date: "`r format(Sys.time(), '%d. %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


# CRAN
library(tidyverse)
library(pxR)
library(pxweb)
library(writexl)
library(readxl)
# library(expss)
# library(statgl)

doPxDir     <- file.path("DO_PX")
workPath    <- file.path(doPxDir, "tmp")
dataPath    <- file.path(doPxDir, "datasaet")
pgmPath     <- file.path(doPxDir, "pgm")
resultsPath <- file.path(doPxDir, "results")
metaPath    <- file.path(doPxDir, "metadata")


```

## Hent data

Fra Statistikbank:

```{r pressure, echo=FALSE}

# Gemt spørgsmål
# https://bank.stat.gl:443/sq/f36e3638-870f-4697-b001-ae1e9cb81abc
#
# I browser kan definitionbeskrivelse ses med:
# https://bank.stat.gl:443/sqget.asp?f36e3638-870f-4697-b001-ae1e9cb81abc


# sq_data <- read_csv("https://bank.stat.gl/sq/f36e3638-870f-4697-b001-ae1e9cb81abc.csv",
#                      locale = locale(encoding = "latin1"))


# Download data med pxweb (CRAN-pakke)
px_data_raw <- 
  pxweb_get(url = "https://bank.stat.gl/api/v1/da/Greenland/BE/BE01/BE0120/BEXSTA.px",
      query = list("place of birth"   = c("T","N","S"),
       "gender"= "*",
       "time"= c("2018","2019","2020","2021","2022"))
)

# Convert to data.frame 
px_data_new <- as.data.frame(px_data_raw, 
                               column.name.type = "code",
                               variable.value.type = "code"
                            ) %>% 
  select(pob=`place of birth`,
         gender,
         time,
         count=`Befolkningen 1. januar`) %>% 
#  mutate(time=strtoi(time)) %>% 
  select(pob,gender,time,value=count) %>% 
  arrange(pob,gender,time)


PXMATRIX <- "BEXTESTNy"
langs <- c("en","da","kl")

# getModified xlsx
source(file.path(pgmPath,"getModifiedXLSX.R"))


# to lists

lst_time_filter <- tidy_Variables %>% 
  filter(toupper(type)=="TIME") %>% 
  distinct(VarName, lang, lVarName)

lst_time_filter <- tidy_Variables %>% 
  filter(toupper(type)=="TIME") %>% 
  distinct(VarName="time", lang, lVarName)

lst_time <- px_data_new %>% 
#  filter(lst_time_filter) %>% 
  distinct(time) %>% 
  mutate(
    code = glue::glue('"{time}"'),
    value = glue::glue('"{time}"')
  ) %>% 
    group_by(time) %>%
  nest(bob = time:value) %>%
  mutate(
    list = map(bob, pull, code),
    value = map_chr(list, paste0, collapse = ","),
    VarName="time"
  ) %>% 
  select(VarName,value) %>% 
  left_join(lst_time_filter) %>% 
  select(lVarName,lang, value) %>% 
    mutate(CODES = paste0('CODES[',lang,']("',lVarName,'")'),
         VALUES = paste0('VALUES[',lang,']("',lVarName,'")')) %>% 
    select(VALUES,value) %>% 
  deframe()


lst_CODES <- tidy_Codelists_lang %>% 
  select(CODES, VALUES, code, value) %>%
  mutate(
    code = glue::glue('"{code}"'),
    value = glue::glue('"{value}"')
  ) %>%
  group_by(CODES) %>%
  nest(bob = VALUES:value) %>%
  mutate(
    list = map(bob, pull, code),
    value = map_chr(list, paste0, collapse = ","),
    CODES = CODES %>% str_remove_all("\\[en]")
  ) %>% 
  select(CODES,value) %>% 
  deframe()
  
lst_VALUES <- tidy_Codelists_lang %>% 
  select(CODES, VALUES, code, value) %>%
    dplyr::mutate(VALUES=across(VALUES,str_replace_all," ",".")) %>%
  dplyr::mutate(
    code = glue::glue('"{code}"'),
    value = glue::glue('"{value}"')
  ) %>%
  group_by(VALUES) %>%
  nest(bob = c(CODES, code, value)) %>%
  dplyr::mutate(
    list = map(bob, pull, value),
    value = map_chr(list, paste0, collapse = ","),
    VALUES = VALUES  %>% str_remove_all("\\[en]") 
  )%>% 
  select(VALUES,value) %>% 
  deframe()


lst_General <- tidy_General |> mutate(name = "{keyword}[{lang}]" |> glue::glue() %>% str_remove_all("\\[en]")) %>% 
  select(name,value) %>% 
  deframe()

lst_stub <-tidy_Variables %>% 
  filter(position %>% str_detect("s")) %>% 
  arrange(position) %>%
  select(lang, lVarName) %>% 
  dplyr::mutate(lVarName=across(lVarName,str_replace_all," ",".")) %>%
  dplyr::mutate(lang = glue::glue('STUB[{lang}]') %>%
           str_remove_all("\\[en]")) %>% 
    group_by(lang) %>%
  nest(data = lVarName) %>%
  dplyr::mutate(
    list = map(data, pull, lVarName),
    value = map_chr(list, paste, collapse = "\",\"") %>% 
      str_sub(3,-2)) %>% 
  select(lang,value) %>% 
  deframe()

lst_head <-tidy_Variables %>% 
  filter(position %>% str_detect("h")) %>% 
  arrange(position) %>%
  select(lang, lVarName) %>%
  mutate(lang = glue::glue('HEADING[{lang}]') %>% str_remove_all("\\[en]")) %>% 
  group_by(lang) %>%
  nest(data = lVarName) %>%
  mutate(
    list = map(data, pull, lVarName),
    value = map_chr(list, paste, collapse = "\",\"")) %>% 
  select(lang,value) %>% 
  deframe()

lst_precision <- tidy_precision %>% 
  deframe()

lst_elimination <- tidy_Variables |>
  select(lVarName, lang, lelimination) %>%
    mutate(eli=glue::glue('ELIMINATION[{lang}]("{lVarName}")'),
    eli = eli  %>% str_remove_all("\\[en]") 
  ) %>% 
  select(eli,lelimination) %>% 
  drop_na(lelimination) %>% 
  mutate(lelimination = ifelse(!lelimination %in% c("YES","NO"), paste0('"',lelimination,'"'),lelimination)) %>% 
  deframe()

lst_General_nolang <- tidy_General_noLang %>% 
  deframe()

meta_list <- lst_General_nolang %>% 
  append(lst_General) %>%
  append(lst_stub) %>%
  append(lst_head) %>%
  append(lst_VALUES) %>%
  append(lst_time) %>%
  append(lst_CODES) %>%
  append(lst_elimination) %>% 
  append(lst_precision)

hi <- enframe(meta_list)

VarNames <- tidy_Variables %>% filter(lang=="en") %>% select(lVarName)

px_data <- px_data_new %>% select(time,
                              place.of.birth=pob,
                              gender=gender,
                              value) %>%
  filter(!is.infinite(value))


px <- px_data |> as.px(list.keys = meta_list)


px[['VALUES']] <- NULL

px$`CREATION-DATE`$value <- format(Sys.time(), "%Y%m%d %H:%M")

px[['TITLE']] <- px$DESCRIPTION
px[['TITLE[da]']] <- px$`DESCRIPTION[da]`
px[['TITLE[kl]']] <- px$`DESCRIPTION[kl]`

px[['LAST-UPDATE']] <- NULL
px$`LAST-UPDATED`$value <- format(Sys.time(), "%Y%m%d %H:%M")  

px[['NEXT-UPDATE']] <- NULL
px$`NEXT-UPDATE`$value <- format(Sys.time(), "%Y%m%d %H:%M") 
px$LANGUAGE$value <- "en"
px$LANGUAGES$value <- langs

px[['DECIMALS']] <- NULL

px$DECIMALS$value <- tidy_General_noLang  %>% filter(keyword=="DECIMALS") %>% select(value) %>%  as.character()

px[['SHOWDECIMAL']] <- NULL

px$SHOWDECIMALS$value <- tidy_General_noLang  %>% filter(keyword=="SHOWDECIMAL") %>% select(value) %>%  as.character()

px$MATRIX$value <- PXMATRIX

# write multilingual px file (based on pxR)
source(file.path(pgmPath, "writepx.R"))

px |> writepx.gs(file.path(resultsPath,paste0(px$MATRIX$value,".px")))



```

