---
title: "micromake"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{micromake}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Install.
```{r, eval= FALSE}
devtools::install_github('StatisticsGreenland/pxmake',
                         ref = '176-mikrodata',
                         upgrade = "never"
                         )
```

Load libraries.

```{r setup, message=FALSE}
packageVersion('pxmake')

library(pxmake)
library(dplyr)
```

Open data.

```{r}
df <- 
  "micro.rds" %>%
    readRDS() %>%
    dplyr::as_tibble() %>%
    dplyr::mutate(sidedoer = stringr::str_trim(sidedoer),
                  sidedoer = dplyr::na_if(sidedoer, "")
                  ) %>%
    dplyr::mutate(across(where(is.numeric), ~ cut(.x, breaks = pretty(.x))))

df
```

Create a metadata template.

```{r, eval=FALSE}
micro_metadata <- 'micro.xlsx' 
make_template(data_df = df, 
              languages = c("en"),
              time_variable = "taar",
              figures_variable = "n", # Important, figures_variable *has* to be "n"
              out_path = micro_metadata
              )
```

The template can be used as is, or it can be edited in Excel to fill in more metadata. Either way, run `micromake` to create the px-files.

```{r, eval=FALSE}
micromake(data_df = df, 
          metadata_path = micro_metadata,
          out_dir = file.path(getwd(), 'tmp') 
          )
```

The px-files can be found in `out_dir` which in this example is the working directory.
