#' Get PX keywords
#' @return data frame with all PX keywords
get_px_keywords <- function() {
  tibble::tribble(
                                 ~keyword, ~mandatory,
                                "CHARSET",      FALSE,
                           "AXIS-VERSION",      FALSE,
                               "CODEPAGE",      FALSE,
                               "LANGUAGE",      FALSE,
                              "LANGUAGES",      FALSE,
                          "CREATION-DATE",      FALSE,
                            "NEXT-UPDATE",      FALSE,
                              "PX-SERVER",      FALSE,
                         "DIRECTORY-PATH",      FALSE,
                       "UPDATE-FREQUENCY",      FALSE,
                                "TABLEID",      FALSE,
                               "SYNONYMS",      FALSE,
                          "DEFAULT-GRAPH",      FALSE,
                               "DECIMALS",       TRUE,
                           "SHOWDECIMALS",      FALSE,
                               "ROUNDING",      FALSE,
                                 "MATRIX",       TRUE,
                          "AGGREGALLOWED",      FALSE,
                                "AUTOPEN",      FALSE,
                           "SUBJECT-CODE",       TRUE,
                           "SUBJECT-AREA",       TRUE,
                           "CONFIDENTIAL",      FALSE,
                              "COPYRIGHT",      FALSE,
                            "DESCRIPTION",       TRUE,
                                  "TITLE",       TRUE,
                     "DESCRIPTIONDEFAULT",      FALSE,
                               "CONTENTS",       TRUE,
                                  "UNITS",       TRUE,
                                   "STUB",       TRUE,
                                "HEADING",       TRUE,
                           "CONTVARIABLE",      FALSE,
                                 "VALUES",       TRUE,
                                "TIMEVAL",      FALSE,
                                  "CODES",      FALSE,
                           "DOUBLECOLUMN",      FALSE,
                               "PRESTEXT",      FALSE,
                                 "DOMAIN",      FALSE,
                          "VARIABLE-TYPE",      FALSE,
                            "HIERARCHIES",      FALSE,
                        "HIERARCHYLEVELS",      FALSE,
                    "HIERARCHYLEVELSOPEN",      FALSE,
                         "HIERARCHYNAMES",      FALSE,
                                    "MAP",      FALSE,
                            "PARTITIONED",      FALSE,
                            "ELIMINATION",      FALSE,
                              "PRECISION",      FALSE,
                           "LAST-UPDATED",      FALSE,
                                "STOCKFA",      FALSE,
                               "CFPRICES",      FALSE,
                                 "DAYADJ",      FALSE,
                                "SEASADJ",      FALSE,
                                "CONTACT",      FALSE,
                              "REFPERIOD",      FALSE,
                             "BASEPERIOD",      FALSE,
                               "DATABASE",      FALSE,
                                 "SOURCE",      FALSE,
                                 "SURVEY",      FALSE,
                                   "LINK",      FALSE,
                               "INFOFILE",      FALSE,
                        "FIRST-PUBLISHED",      FALSE,
                                "META-ID",      FALSE,
                    "OFFICIAL-STATISTICS",      FALSE,
                                   "INFO",      FALSE,
                                  "NOTEX",      FALSE,
                                   "NOTE",      FALSE,
                             "VALUENOTEX",      FALSE,
                              "VALUENOTE",      FALSE,
                              "CELLNOTEX",      FALSE,
                               "CELLNOTE",      FALSE,
                            "DATASYMBOL1",      FALSE,
                            "DATASYMBOL2",      FALSE,
                            "DATASYMBOL3",      FALSE,
                            "DATASYMBOL4",      FALSE,
                            "DATASYMBOL5",      FALSE,
                            "DATASYMBOL6",      FALSE,
                          "DATASYMBOLSUM",      FALSE,
                          "DATASYMBOLNIL",      FALSE,
                           "DATANOTECELL",      FALSE,
                            "DATANOTESUM",      FALSE,
                               "DATANOTE",      FALSE,
                                   "KEYS",      FALSE,
                           "ATTRIBUTE-ID",      FALSE,
                         "ATTRIBUTE-TEXT",      FALSE,
                             "ATTRIBUTES",      FALSE,
                                   "DATA",      TRUE
                    ) %>%
    dplyr::mutate(order = dplyr::row_number())
}

# datapasta::tribble_paste(x)
# tibble::tribble(
#                ~keyword, ~mandatory, ~metadata_sheet,
#               "CHARSET",      FALSE,              "General",
#          "AXIS-VERSION",      FALSE,              "General",
#              "CODEPAGE",      FALSE,              NA,
#              "LANGUAGE",      FALSE,              "General",
#             "LANGUAGES",      FALSE,              "General",
#         "CREATION-DATE",      FALSE,              "General",
#           "NEXT-UPDATE",      FALSE,              "General",
#             "PX-SERVER",      FALSE,              "General",
#        "DIRECTORY-PATH",      FALSE,              "General",
#      "UPDATE-FREQUENCY",      FALSE,              "General",
#               "TABLEID",      FALSE,              "General",
#              "SYNONYMS",      FALSE,              "General",
#         "DEFAULT-GRAPH",      FALSE,              "General",
#              "DECIMALS",       TRUE,              "General",
#          "SHOWDECIMALS",      FALSE,              "General",
#              "ROUNDING",      FALSE,              "General",
#                "MATRIX",       TRUE,              "General",
#         "AGGREGALLOWED",      FALSE,              "General",
#               "AUTOPEN",      FALSE,              "General",
#          "SUBJECT-CODE",       TRUE,              "General",
#          "SUBJECT-AREA",       TRUE,              "General",
#          "CONFIDENTIAL",      FALSE,              "General",
#             "COPYRIGHT",      FALSE,              "General",
#           "DESCRIPTION",       TRUE,              "General",
#                 "TITLE",       TRUE,              "General",
#    "DESCRIPTIONDEFAULT",      FALSE,              "General",
#              "CONTENTS",       TRUE,              "General",
#                 "UNITS",       TRUE,              "General",
#                  "STUB",       TRUE,              "General",
#               "HEADING",       TRUE,              "General",
#          "CONTVARIABLE",      FALSE,              "General",
#                "VALUES",       TRUE,              NA,
#               "TIMEVAL",      FALSE,              NA,
#                 "CODES",      FALSE,              "Codelists",
#          "DOUBLECOLUMN",      FALSE,              NA,
#              "PRESTEXT",      FALSE,              NA,
#                "DOMAIN",      FALSE,              NA,
#         "VARIABLE-TYPE",      FALSE,              "Variables",
#           "HIERARCHIES",      FALSE,              NA,
#       "HIERARCHYLEVELS",      FALSE,              NA,
#   "HIERARCHYLEVELSOPEN",      FALSE,              NA,
#        "HIERARCHYNAMES",      FALSE,              NA,
#                   "MAP",      FALSE,              NA,
#           "PARTITIONED",      FALSE,              NA,
#           "ELIMINATION",      FALSE,              "Variables",
#             "PRECISION",      FALSE,              NA,
#          "LAST-UPDATED",      FALSE,              NA,
#               "STOCKFA",      FALSE,              NA,
#              "CFPRICES",      FALSE,              NA,
#                "DAYADJ",      FALSE,              NA,
#               "SEASADJ",      FALSE,              NA,
#               "CONTACT",      FALSE,              NA,
#             "REFPERIOD",      FALSE,              NA,
#            "BASEPERIOD",      FALSE,              NA,
#              "DATABASE",      FALSE,              NA,
#                "SOURCE",      FALSE,              NA,
#                "SURVEY",      FALSE,              NA,
#                  "LINK",      FALSE,              NA,
#              "INFOFILE",      FALSE,              NA,
#       "FIRST-PUBLISHED",      FALSE,              NA,
#               "META-ID",      FALSE,              NA,
#   "OFFICIAL-STATISTICS",      FALSE,              NA,
#                  "INFO",      FALSE,              NA,
#                 "NOTEX",      FALSE,              "General",
#                  "NOTE",      FALSE,              "Variables",
#            "VALUENOTEX",      FALSE,              NA,
#             "VALUENOTE",      FALSE,              NA,
#             "CELLNOTEX",      FALSE,              NA,
#              "CELLNOTE",      FALSE,              NA,
#           "DATASYMBOL1",      FALSE,              NA,
#           "DATASYMBOL2",      FALSE,              NA,
#           "DATASYMBOL3",      FALSE,              NA,
#           "DATASYMBOL4",      FALSE,              NA,
#           "DATASYMBOL5",      FALSE,              NA,
#           "DATASYMBOL6",      FALSE,              NA,
#         "DATASYMBOLSUM",      FALSE,              NA,
#         "DATASYMBOLNIL",      FALSE,              NA,
#          "DATANOTECELL",      FALSE,              NA,
#           "DATANOTESUM",      FALSE,              NA,
#              "DATANOTE",      FALSE,              NA,
#                  "KEYS",      FALSE,              NA,
#          "ATTRIBUTE-ID",      FALSE,              NA,
#        "ATTRIBUTE-TEXT",      FALSE,              NA,
#            "ATTRIBUTES",      FALSE,              NA,
#                  "DATA",       TRUE,              NA
#   )
