#' Get PX keywords
#'
#' The row order reflex the recommend sort order in the px-file specification.
#'
#' @return data frame with all PX keywords
get_px_keywords <- function() {
  tibble::tribble(
                                 ~keyword, ~mandatory, ~metadata_sheet,
                                "CHARSET",      FALSE,       "General",
                           "AXIS-VERSION",      FALSE,       "General",
                               "CODEPAGE",      FALSE,              NA,
                               "LANGUAGE",      FALSE,       "General",
                              "LANGUAGES",      FALSE,       "General",
                          "CREATION-DATE",      FALSE,       "General",
                            "NEXT-UPDATE",      FALSE,       "General",
                              "PX-SERVER",      FALSE,              NA,
                         "DIRECTORY-PATH",      FALSE,              NA,
                       "UPDATE-FREQUENCY",      FALSE,       "General",
                                "TABLEID",      FALSE,              NA,
                               "SYNONYMS",      FALSE,              NA,
                          "DEFAULT-GRAPH",      FALSE,              NA,
                               "DECIMALS",       TRUE,       "General",
                           "SHOWDECIMALS",      FALSE,       "General",
                               "ROUNDING",      FALSE,              NA,
                                 "MATRIX",       TRUE,       "General",
                          "AGGREGALLOWED",      FALSE,              NA,
                                "AUTOPEN",      FALSE,              NA,
                           "SUBJECT-CODE",       TRUE,       "General",
                           "SUBJECT-AREA",       TRUE,       "General",
                           "CONFIDENTIAL",      FALSE,       "General",
                              "COPYRIGHT",      FALSE,       "General",
                            "DESCRIPTION",       TRUE,       "General",
                                  "TITLE",       TRUE,       "General",
                     "DESCRIPTIONDEFAULT",      FALSE,              NA,
                               "CONTENTS",       TRUE,       "General",
                                  "UNITS",       TRUE,       "General",
                                   "STUB",       TRUE,              NA,
                                "HEADING",       TRUE,              NA,
                           "CONTVARIABLE",      FALSE,              NA,
                                 "VALUES",       TRUE,              NA,
                                "TIMEVAL",      FALSE,              NA,
                                  "CODES",      FALSE,     "Codelists",
                           "DOUBLECOLUMN",      FALSE,              NA,
                               "PRESTEXT",      FALSE,              NA,
                                 "DOMAIN",      FALSE,     "Variables",
                          "VARIABLE-TYPE",      FALSE,     "Variables",
                            "HIERARCHIES",      FALSE,              NA,
                        "HIERARCHYLEVELS",      FALSE,              NA,
                    "HIERARCHYLEVELSOPEN",      FALSE,              NA,
                         "HIERARCHYNAMES",      FALSE,              NA,
                                    "MAP",      FALSE,              NA,
                            "PARTITIONED",      FALSE,              NA,
                            "ELIMINATION",      FALSE,     "Variables",
                              "PRECISION",      FALSE,              NA,
                           "LAST-UPDATED",      FALSE,              NA,
                                "STOCKFA",      FALSE,              NA,
                               "CFPRICES",      FALSE,              NA,
                                 "DAYADJ",      FALSE,              NA,
                                "SEASADJ",      FALSE,              NA,
                                "CONTACT",      FALSE,              NA,
                              "REFPERIOD",      FALSE,              NA,
                             "BASEPERIOD",      FALSE,              NA,
                               "DATABASE",      FALSE,              NA,
                                 "SOURCE",      FALSE,              NA,
                                 "SURVEY",      FALSE,              NA,
                                   "LINK",      FALSE,              NA,
                               "INFOFILE",      FALSE,              NA,
                        "FIRST-PUBLISHED",      FALSE,              NA,
                                "META-ID",      FALSE,              NA,
                    "OFFICIAL-STATISTICS",      FALSE,              NA,
                                   "INFO",      FALSE,              NA,
                                  "NOTEX",      FALSE,       "General",
                                   "NOTE",      FALSE,     "Variables",
                             "VALUENOTEX",      FALSE,              NA,
                              "VALUENOTE",      FALSE,              NA,
                              "CELLNOTEX",      FALSE,              NA,
                               "CELLNOTE",      FALSE,              NA,
                            "DATASYMBOL1",      FALSE,              NA,
                            "DATASYMBOL2",      FALSE,              NA,
                            "DATASYMBOL3",      FALSE,              NA,
                            "DATASYMBOL4",      FALSE,              NA,
                            "DATASYMBOL5",      FALSE,              NA,
                            "DATASYMBOL6",      FALSE,              NA,
                          "DATASYMBOLSUM",      FALSE,              NA,
                          "DATASYMBOLNIL",      FALSE,              NA,
                           "DATANOTECELL",      FALSE,              NA,
                            "DATANOTESUM",      FALSE,              NA,
                               "DATANOTE",      FALSE,              NA,
                                   "KEYS",      FALSE,              NA,
                           "ATTRIBUTE-ID",      FALSE,              NA,
                         "ATTRIBUTE-TEXT",      FALSE,              NA,
                             "ATTRIBUTES",      FALSE,              NA,
                                   "DATA",       TRUE,              NA
                    ) %>%
    dplyr::mutate(order = dplyr::row_number())
}
