#' Get PX keywords
#'
#' The row order reflects the recommended sort order in the px-file specification.
#'
#' @return data frame with all PX keywords
get_px_keywords <- function() {
  tibble::tribble(
               ~keyword, ~mandatory, ~in_table_sheet, ~language_dependent, ~indexed_by_contvariable, ~quote_value,
              "CHARSET",      FALSE,            TRUE,               FALSE,                    FALSE,         TRUE,
         "AXIS-VERSION",      FALSE,            TRUE,               FALSE,                    FALSE,         TRUE,
             "CODEPAGE",      FALSE,            TRUE,               FALSE,                    FALSE,         TRUE,
             "LANGUAGE",      FALSE,            TRUE,               FALSE,                    FALSE,         TRUE,
            "LANGUAGES",      FALSE,            TRUE,               FALSE,                    FALSE,         TRUE,
        "CREATION-DATE",      FALSE,            TRUE,               FALSE,                    FALSE,         TRUE,
          "NEXT-UPDATE",      FALSE,            TRUE,               FALSE,                    FALSE,         TRUE,
            "PX-SERVER",      FALSE,           FALSE,               FALSE,                    FALSE,         TRUE,
       "DIRECTORY-PATH",      FALSE,           FALSE,               FALSE,                    FALSE,         TRUE,
     "UPDATE-FREQUENCY",      FALSE,            TRUE,               FALSE,                    FALSE,         TRUE,
              "TABLEID",      FALSE,            TRUE,               FALSE,                    FALSE,         TRUE,
             "SYNONYMS",      FALSE,           FALSE,               FALSE,                    FALSE,         TRUE,
        "DEFAULT-GRAPH",      FALSE,           FALSE,               FALSE,                    FALSE,        FALSE,
             "DECIMALS",       TRUE,            TRUE,               FALSE,                    FALSE,        FALSE,
         "SHOWDECIMALS",      FALSE,            TRUE,               FALSE,                    FALSE,        FALSE,
             "ROUNDING",      FALSE,           FALSE,               FALSE,                    FALSE,        FALSE,
               "MATRIX",       TRUE,            TRUE,               FALSE,                    FALSE,         TRUE,
        "AGGREGALLOWED",      FALSE,            TRUE,               FALSE,                    FALSE,        FALSE,
              "AUTOPEN",      FALSE,            TRUE,               FALSE,                    FALSE,        FALSE,
         "SUBJECT-CODE",       TRUE,            TRUE,               FALSE,                    FALSE,         TRUE,
         "SUBJECT-AREA",       TRUE,            TRUE,                TRUE,                    FALSE,         TRUE,
         "CONFIDENTIAL",      FALSE,            TRUE,               FALSE,                    FALSE,        FALSE,
            "COPYRIGHT",      FALSE,            TRUE,               FALSE,                    FALSE,         TRUE,
          "DESCRIPTION",       TRUE,            TRUE,                TRUE,                    FALSE,         TRUE,
                "TITLE",       TRUE,            TRUE,                TRUE,                    FALSE,         TRUE,
   "DESCRIPTIONDEFAULT",      FALSE,           FALSE,               FALSE,                    FALSE,        FALSE,
             "CONTENTS",       TRUE,            TRUE,                TRUE,                    FALSE,         TRUE,
                "UNITS",       TRUE,            TRUE,                TRUE,                     TRUE,         TRUE,
                 "STUB",       TRUE,           FALSE,                TRUE,                    FALSE,         TRUE,
              "HEADING",       TRUE,           FALSE,                TRUE,                    FALSE,         TRUE,
         "CONTVARIABLE",      FALSE,            TRUE,                TRUE,                    FALSE,         TRUE,
               "VALUES",       TRUE,           FALSE,                TRUE,                    FALSE,         TRUE,
              "TIMEVAL",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
                "CODES",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
         "DOUBLECOLUMN",      FALSE,           FALSE,               FALSE,                    FALSE,        FALSE,
             "PRESTEXT",      FALSE,           FALSE,                TRUE,                    FALSE,        FALSE,
               "DOMAIN",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
        "VARIABLE-TYPE",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
         "VARIABLECODE",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
          "HIERARCHIES",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
      "HIERARCHYLEVELS",      FALSE,           FALSE,                TRUE,                    FALSE,        FALSE,
  "HIERARCHYLEVELSOPEN",      FALSE,           FALSE,                TRUE,                    FALSE,        FALSE,
       "HIERARCHYNAMES",      FALSE,           FALSE,               FALSE,                    FALSE,         TRUE,
                  "MAP",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
          "PARTITIONED",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
          "ELIMINATION",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
            "PRECISION",      FALSE,           FALSE,                TRUE,                    FALSE,        FALSE,
         "LAST-UPDATED",      FALSE,            TRUE,                TRUE,                     TRUE,         TRUE,
              "STOCKFA",      FALSE,           FALSE,                TRUE,                     TRUE,         TRUE,
             "CFPRICES",      FALSE,           FALSE,                TRUE,                     TRUE,         TRUE,
               "DAYADJ",      FALSE,           FALSE,                TRUE,                     TRUE,        FALSE,
              "SEASADJ",      FALSE,           FALSE,                TRUE,                     TRUE,        FALSE,
              "CONTACT",      FALSE,            TRUE,                TRUE,                     TRUE,         TRUE,
            "REFPERIOD",      FALSE,           FALSE,                TRUE,                     TRUE,         TRUE,
           "BASEPERIOD",      FALSE,           FALSE,                TRUE,                     TRUE,         TRUE,
             "DATABASE",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
               "SOURCE",      FALSE,            TRUE,                TRUE,                    FALSE,         TRUE,
               "SURVEY",      FALSE,           FALSE,               FALSE,                    FALSE,         TRUE,
                 "LINK",      FALSE,            TRUE,                TRUE,                    FALSE,         TRUE,
             "INFOFILE",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
      "FIRST-PUBLISHED",      FALSE,           FALSE,               FALSE,                    FALSE,         TRUE,
              "META-ID",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
  "OFFICIAL-STATISTICS",      FALSE,           FALSE,               FALSE,                    FALSE,        FALSE,
                 "INFO",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
                "NOTEX",      FALSE,            TRUE,                TRUE,                    FALSE,         TRUE,
                 "NOTE",      FALSE,            TRUE,                TRUE,                    FALSE,         TRUE,
           "VALUENOTEX",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
            "VALUENOTE",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
            "CELLNOTEX",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
             "CELLNOTE",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
          "DATASYMBOL1",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
          "DATASYMBOL2",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
          "DATASYMBOL3",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
          "DATASYMBOL4",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
          "DATASYMBOL5",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
          "DATASYMBOL6",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
        "DATASYMBOLSUM",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
        "DATASYMBOLNIL",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
         "DATANOTECELL",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
          "DATANOTESUM",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
             "DATANOTE",      FALSE,           FALSE,               FALSE,                    FALSE,         TRUE,
                 "KEYS",      FALSE,           FALSE,                TRUE,                    FALSE,        FALSE,
         "ATTRIBUTE-ID",      FALSE,           FALSE,               FALSE,                    FALSE,         TRUE,
       "ATTRIBUTE-TEXT",      FALSE,           FALSE,                TRUE,                    FALSE,         TRUE,
           "ATTRIBUTES",      FALSE,           FALSE,               FALSE,                    FALSE,         TRUE,
                 "DATA",       TRUE,           FALSE,               FALSE,                    FALSE,         TRUE
  ) %>%
  dplyr::mutate(order = dplyr::row_number())
}
